[platformio]
build_dir = C:\PIO_Builds\QBOT

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

; מונע מה-Serial Monitor למשוך את הצ'יפ למצב Bootloader באתחול
monitor_dtr = 0
monitor_rts = 0

; הגדרות זיכרון נכונות ומקוריות עבור ה-N16R8 (OPI)
board_build.arduino.memory_type = qio_opi
board_build.f_flash = 80000000L
board_build.f_cpu = 240000000L

; דגלי קומפילציה קריטיים למניעת קפיאה באתחול ה-PSRAM
build_flags = 
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DCORE_DEBUG_LEVEL=5             ; מעלה את רמת הדיבאג למקסימום כדי לראות בדיוק איפה הוא נתקע

lib_deps =
    adafruit/Adafruit SSD1306 @ ^2.5.13
    adafruit/Adafruit GFX Library @ ^1.11.11